# NumPy - Numerical Python 

### Developed by - Travis Oliphant (1995)
#### Initially named Numeric 
#### Got named NumPy in 2006

##### It lets you work with huge multidimensional arrays and matrices.
##### It also provides tons of high level mathematical functions for Scientific computation.
##### Its Python alternative to MATLAB ( Matrix Laboratry).
##### Can be used for Fourier transfromation , Linear Algebra , random numbers generation , Shape manipulation & much more.

In [9]:
# Importing required library
import numpy as np
import sys

###  Creating 1D array & basic properties

In [10]:
arr_1d = np.array(range(1,11))
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr_1d.dtype

dtype('int32')

In [12]:
type(arr_1d)

numpy.ndarray

In [13]:
# Get dimension of any array
arr_1d.ndim

1

In [14]:
# Get size of array
arr_1d.size

10

In [15]:
# Shape of any array
arr_1d.shape

(10,)

In [16]:
# Strides means how many bytes to be skip to move to next element
arr_1d.strides

(4,)

In [17]:
arr2 = np.array([1,2,3,4,5,'a'])
arr2

array(['1', '2', '3', '4', '5', 'a'], dtype='<U11')

In [18]:
arr2.dtype

dtype('<U11')

###### NumPy arrays can take homogenous elements (data of same type) inside it, but it holds exception while numpy array has dtype of object.

In [19]:
arr = np.array(([1,2,3,4,5], str('Rajat')),dtype=object)
arr

array([list([1, 2, 3, 4, 5]), 'Rajat'], dtype=object)

### NumPy array VS Python List

In [20]:
l = list(range(1,11))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [21]:
# Multiplying list by 2 
l1 = l * 2
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [22]:
# Getting bytes of memory used
l1.__sizeof__(),arr_1d.__sizeof__()

(200, 152)

In [23]:
# Another method to check used memory in bytes
sys.getsizeof(l1),sys.getsizeof(arr_1d)

(216, 152)

In [24]:
# Multiplying numpy array by 2
arr1 = arr_1d * 2
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Creating an 2D array from an 1D array

In [25]:
# Reshape changes the shape of array to the desired shape
arr_2d = arr_1d.reshape(2,5)
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
arr_2d.ndim

2

In [27]:
# First value represents 20 bytes need to be skipped to move to next row and 4 bytes to next element in same row
arr_2d.strides

(20, 4)

In [28]:
# Similarily can change dtype of elements inside array
arr1_f = np.array(arr_2d,dtype= float)
arr1_f

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

## Slicing & Indexing

##### Slicing & Indexing in 1D array is same like Python list.

In [29]:
arr_1d[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr_1d[7]

8

In [31]:
arr_1d[0] = 0
arr_1d

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr_1d[2:6]

array([3, 4, 5, 6])

In [33]:
arr_1d[-3:-1]

array([8, 9])

##### Slicing & Indexing in 2D array is somehow different.

In [34]:
arr_2d[:]

array([[ 0,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
# Returns index for maximum value
arr_2d.argmax()

9

In [36]:
# Returns index for minuimum value
arr_2d.argmin()

0

In [37]:
# Returns True if any of value is True like any()
arr_2d.any()

True

In [38]:
# Returns True only if all values are True like all() 
arr_2d.all()

False

In [39]:
arr_2d[0]

array([0, 2, 3, 4, 5])

In [40]:
arr_2d[1]

array([ 6,  7,  8,  9, 10])

In [41]:
arr_2d[0][0:3]

array([0, 2, 3])

In [42]:
arr_2d[1][:-1]

array([6, 7, 8, 9])

##### NumPy arrays can be accessed using rows and columns indexing.

In [43]:
arr_2d[0:2,:1]

array([[0],
       [6]])

In [44]:
arr_2d[0:3,1:3]

array([[2, 3],
       [7, 8]])

In [45]:
arr_2d[1,:-1]

array([6, 7, 8, 9])

## Filtering & Boolean Indexing

In [46]:
arr_1d > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [47]:
arr_1d[arr_1d > 5]

array([ 6,  7,  8,  9, 10])

In [48]:
arr_2d[arr_2d < 4]

array([0, 2, 3])

In [49]:
np.where(arr_2d > 3, arr_2d , np.NaN)

array([[nan, nan, nan,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

## Mathematical Functions on NumPy arrays

In [50]:
arr_2d * 2

array([[ 0,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [51]:
arr_2d + 3

array([[ 3,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13]])

In [52]:
arr_2d - arr_1d.reshape(2,5)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [53]:
arr_2d

array([[ 0,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [54]:
# Axis = None by default will flattened any dimension array into 1D array
arr_2d.mean()

5.4

In [55]:
# Axis = 0 will calculate along Columns
arr_2d.mean(axis = 0)

array([3. , 4.5, 5.5, 6.5, 7.5])

In [56]:
# axis = 1 will calculate along Rows
arr_2d.mean(axis =1)

array([2.8, 8. ])

In [57]:
np.mean(arr_2d , axis = 0)

array([3. , 4.5, 5.5, 6.5, 7.5])

In [58]:
np.sum(arr_2d , axis = None)

54

In [59]:
arr_2d.sum()

54

In [60]:
arr_2d.sum(axis = 1)

array([14, 40])

In [61]:
np.sum(arr_2d , axis = 0)

array([ 6,  9, 11, 13, 15])

## Concatenating NumPy arrays

In [62]:
arr_a = np.array([[1,2],[3,4]])
arr_b = np.array([[6,8]])
# Shape of both arrays should be of same shape
np.concatenate((arr_a , arr_b) ,axis = None)

array([1, 2, 3, 4, 6, 8])

In [63]:
np.concatenate((arr_a , arr_b) , axis = 0)

array([[1, 2],
       [3, 4],
       [6, 8]])

In [64]:
np.concatenate((arr_a , arr_b.T), axis = 1)

array([[1, 2, 6],
       [3, 4, 8]])

In [65]:
np.dot([[1,2],[3,4]],[[3,5],[7,9]])

array([[17, 23],
       [37, 51]])

## Generating different types of NumPy arrays Programmatically

In [66]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [70]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [71]:
a = np.array([1,2,3,4,5,6,7,8], ndmin= 2)
a

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [72]:
a.ndim

2

In [73]:
a.size

8

In [74]:
a.itemsize

4

In [75]:
a.shape

(1, 8)

In [76]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [77]:
help(a.flags)

Help on flagsobj object:

class flagsobj(builtins.object)
 |  Methods defined here:
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __ne__(self, value, /)
 |      Return self!=value.
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  __setitem__(self, key, value, /)
 |      Set self[key] to value.
 |  
 |  __str__(self, /)
 |      Return str(self).
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  -

In [78]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [79]:
# Creates array of eveny spaced array between two values
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [80]:
np.empty([2,3])

array([[1., 0., 0.],
       [0., 1., 0.]])

In [81]:
help(np.empty_like)

Help on function empty_like in module numpy:

empty_like(...)
    empty_like(prototype, dtype=None, order='K', subok=True, shape=None)
    
    Return a new array with the same shape and type as a given array.
    
    Parameters
    ----------
    prototype : array_like
        The shape and data-type of `prototype` define these same attributes
        of the returned array.
    dtype : data-type, optional
        Overrides the data type of the result.
    
        .. versionadded:: 1.6.0
    order : {'C', 'F', 'A', or 'K'}, optional
        Overrides the memory layout of the result. 'C' means C-order,
        'F' means F-order, 'A' means 'F' if `prototype` is Fortran
        contiguous, 'C' otherwise. 'K' means match the layout of `prototype`
        as closely as possible.
    
        .. versionadded:: 1.6.0
    subok : bool, optional.
        If True, then the newly created array will use the sub-class
        type of `prototype`, otherwise it will be a base-class array. Defaults


In [82]:
# Filling arrays with random values with desired size
np.random.rand(2,3)

array([[0.37396013, 0.70683412, 0.76781249],
       [0.82786226, 0.2618918 , 0.77084153]])

In [83]:
# Generating array of values from 1 to 10
np.random.rand(10) * 10

array([6.62047228, 2.11803396, 8.4944261 , 2.40935307, 7.93578962,
       3.11399546, 1.05145295, 6.01039016, 2.8910789 , 6.5942019 ])

In [84]:
# Filling random integer in desired shape array
np.random.randint(1,11,(2,3))

array([[4, 5, 9],
       [8, 2, 3]])

In [85]:
# Filling array with random values
np.random.random((3,4))

array([[0.34837109, 0.40400683, 0.53519569, 0.0507116 ],
       [0.0027642 , 0.60996259, 0.69743091, 0.37716179],
       [0.19188464, 0.85525088, 0.61182155, 0.60168847]])

In [86]:
# Filling Normal Gussian Distribution values
np.random.randn(2,3)

array([[-2.50773407,  0.42424805, -1.17586723],
       [-1.05696802,  0.324887  , -0.11874922]])

In [87]:
dig = np.diag([1,2,3])
dig , ~dig

(array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]]),
 array([[-2, -1, -1],
        [-1, -3, -1],
        [-1, -1, -4]]))

In [88]:
np.diag([1,2,3], k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [89]:
np.diag([1,2,3.4], k = -1)

array([[0. , 0. , 0. , 0. ],
       [1. , 0. , 0. , 0. ],
       [0. , 2. , 0. , 0. ],
       [0. , 0. , 3.4, 0. ]])

In [90]:
np.empty_like((1))

array(1)

In [91]:
np.info(np.sum)

 sum(a, axis=None, dtype=None, out=None, keepdims=<no value>,
     initial=<no value>, where=<no value>)

Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used while if `a` is unsigned then an unsigned integer 

In [92]:
np.array_equiv([1,1],[1])

True

In [93]:
np.array_equal([1,2,3],[4.,5])

False

In [94]:
np.allclose([1,2,3],[1,2,3])

True

In [95]:
np.array_equiv([1,2],[1,3])

False

In [96]:
help(np.allclose)

Help on function allclose in module numpy:

allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
    Returns True if two arrays are element-wise equal within a tolerance.
    
    The tolerance values are positive, typically very small numbers.  The
    relative difference (`rtol` * abs(`b`)) and the absolute difference
    `atol` are added together to compare against the absolute difference
    between `a` and `b`.
    
    NaNs are treated as equal if they are in the same place and if
    ``equal_nan=True``.  Infs are treated as equal if they are in the same
    place and of the same sign in both arrays.
    
    Parameters
    ----------
    a, b : array_like
        Input arrays to compare.
    rtol : float
        The relative tolerance parameter (see Notes).
    atol : float
        The absolute tolerance parameter (see Notes).
    equal_nan : bool
        Whether to compare NaN's as equal.  If True, NaN's in `a` will be
        considered equal to NaN's in `b` in the output a

In [97]:
np.array([1,5,3],dtype= complex)

array([1.+0.j, 5.+0.j, 3.+0.j])

## Applying Relational & Logical operators on 2D array

In [98]:
x = np.random.randint(0,6,(2,3))
x

array([[5, 3, 2],
       [4, 1, 0]])

In [99]:
y = np.random.randint(0,6,(2,3))
y

array([[4, 3, 5],
       [0, 0, 1]])

In [100]:
x > y

array([[ True, False, False],
       [ True,  True, False]])

In [101]:
x <= y

array([[False,  True,  True],
       [False, False,  True]])

In [102]:
x == y

array([[False,  True, False],
       [False, False, False]])

In [103]:
np.logical_and(x,y)

array([[ True,  True,  True],
       [False, False, False]])

In [104]:
np.logical_or(x,y)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [105]:
# Basically it's representing first array of rows and second array of columns for index of element satisfying conditions
# Bcoz its a 2D array
np.where(x==y)

(array([0], dtype=int64), array([1], dtype=int64))

In [106]:
np.where(x > 2)

(array([0, 0, 1], dtype=int64), array([0, 1, 0], dtype=int64))

In [107]:
arr_1d

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
# Returns index of element satisfying specific condition
np.where(arr_1d != 5)

(array([0, 1, 2, 3, 5, 6, 7, 8, 9], dtype=int64),)

In [109]:
z = np.random.randint(0,6,(3,2))
x - z.T

array([[ 0,  0, -3],
       [ 4,  0, -2]])

In [110]:
np.transpose(z)

array([[5, 3, 5],
       [0, 1, 2]])

In [111]:
z

array([[5, 0],
       [3, 1],
       [5, 2]])

In [112]:
z.T

array([[5, 3, 5],
       [0, 1, 2]])

### Broadcasting means making arrays compatible internally to do operations.

In [113]:
x

array([[5, 3, 2],
       [4, 1, 0]])

In [114]:
y

array([[4, 3, 5],
       [0, 0, 1]])

In [115]:
x - y

array([[ 1,  0, -3],
       [ 4,  1, -1]])

In [116]:
x - [1,2,3]

array([[ 4,  1, -1],
       [ 3, -1, -3]])

In [117]:
x + [[3],[2]]

array([[8, 6, 5],
       [6, 3, 2]])

In [118]:
x * [[3],[2]]

array([[15,  9,  6],
       [ 8,  2,  0]])

In [119]:
np.resize(x , 10)

array([5, 3, 2, 4, 1, 0, 5, 3, 2, 4])

In [120]:
np.array([1,2,3])+ np.array([7])

array([ 8,  9, 10])

In [121]:
np.array([1,2,3]) + np.array([[1],[2],[3]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])